{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Arsenal team stat\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Arsenal team stat",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6522496-c7ff-4d5d-b98f-1f4248a5353c",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Metric",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "67227061-04b9-4378-acde-a6b75671d947",
            "sortByColumn": "order Index",
            "sourceColumn": "Metric",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e8ffb38-c9d5-4537-a229-6c44c9fb04b6",
            "sourceColumn": "Value",
            "summarizeBy": "none"
          },
          {
            "name": "order Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "036cd1c3-4049-49c8-9d27-1e1fcf59713b",
            "sourceColumn": "order Index",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "6b1cadc3-d659-4c44-a500-233cb9642f70",
        "measures": [
          {
            "name": "Matches Played",
            "expression": [
              "",
              "CALCULATE(",
              "    SELECTEDVALUE('Arsenal team stat'[Value]),",
              "    FILTER('Arsenal team stat', 'Arsenal team stat'[Metric] = \"Matches Played\")",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "b02cc140-a38b-4d37-b138-69292eb146e8"
          },
          {
            "name": "Wins",
            "expression": [
              "",
              "CALCULATE(",
              "    SELECTEDVALUE('Arsenal team stat'[Value]),",
              "    FILTER('Arsenal team stat', 'Arsenal team stat'[Metric] = \"Wins\")",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "28aa6b51-c8b6-4e0d-83d3-addcff90dde6"
          },
          {
            "name": "Losses",
            "expression": [
              "",
              "CALCULATE(",
              "    SELECTEDVALUE('Arsenal team stat'[Value]),",
              "    FILTER('Arsenal team stat', 'Arsenal team stat'[Metric] = \"Losses\")",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "ffd90299-492a-4d20-95a2-7a209c43d333"
          },
          {
            "name": "Goals",
            "expression": [
              "",
              "CALCULATE(",
              "    SELECTEDVALUE('Arsenal team stat'[Value]),",
              "    FILTER('Arsenal team stat', 'Arsenal team stat'[Metric] = \"Goals\")",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "23aadd56-7352-4f7e-bc8c-885bc4014a39"
          },
          {
            "name": "Goals Conceded",
            "expression": [
              "",
              "CALCULATE(",
              "    SELECTEDVALUE('Arsenal team stat'[Value]),",
              "    FILTER('Arsenal team stat', 'Arsenal team stat'[Metric] = \"Goals Conceded\")",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "ecbf4a41-1c9c-4dda-9022-f134613e9a0a"
          },
          {
            "name": "Clean Sheets",
            "expression": [
              "",
              "CALCULATE(",
              "    SELECTEDVALUE('Arsenal team stat'[Value]),",
              "    FILTER('Arsenal team stat', 'Arsenal team stat'[Metric] = \"Clean sheets\")",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "28b14d82-6417-4865-95a9-0aac385192c1"
          }
        ],
        "partitions": [
          {
            "name": "Arsenal team stat-7bcea5e7-d9cf-4bce-940f-e249a407b6c2",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Sifiso.Ndlovu.EUROPCAR\\Documents\\Aresenal team stat.csv\"),[Delimiter=\",\", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Promoted Headers\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Index\",{{\"Index\", \"order Index\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_60fa08ad-c193-4c89-ab5a-9c093d1211fc",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5805d3ea-f52e-4ee3-bb90-be9ba48ce616",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2dcc59a4-503e-4764-95f8-56fcdfd655c2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9dbd8741-81ff-4b92-b959-59c3c7b21bd8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2bfc56b2-769e-4514-83fd-4ce1a8fd1ead",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "adbf37be-15f3-4cb2-8d75-23c5c8dac5bc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "42445ebb-bbc2-4217-975c-502031a57385",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "63048bc7-7a19-4f9e-ad78-136a322c91c2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "36d18695-6051-4a4e-8bc7-419c8c0192ef",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d1b8f4d1-bb2c-43ff-ae35-b1d94e0479de",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "2b7a923b-caf7-4001-9a0a-d9c8c06ec57a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "887e22b3-cd19-4768-a186-b45ea2dddbbb",
                "ordinal": 3
              }
            ],
            "lineageTag": "514083ec-f8a7-49ab-9f3f-6801ad444289"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "f649527b-38b0-46b1-b510-0e4929e97130",
        "partitions": [
          {
            "name": "DateTableTemplate_60fa08ad-c193-4c89-ab5a-9c093d1211fc-040bbade-e0b3-43c5-af31-175fa88ca851",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}